adminapp/urls.py
from django.urls import path, include
from adminapp import views as adminapp

app_name = 'adminapp'


urlpatterns = [
    path('users/', adminapp.UsersListView.as_view(), name= 'users'),
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),


    path('categories/', adminapp.categories, name='categories'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/<int:pk>/', adminapp.products, name='products'),
    path('products/create/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),

]

authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify')
]

basketapp/urls.py
from django.urls import path, include
from basketapp import views as basketapp

app_name = 'basketapp'


urlpatterns = [
    path('', basketapp.basket, name= 'basket'),
    path('add/<int:pk>/', basketapp.basket_add, name='basket_add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='basket_remove'),
    path('edit/<int:pk>/<quantity>/', basketapp.basket_edit, name='basket_edit'),
]

geekshop_2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('contacts/', mainapp.contact, name='contact'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basketapp')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
    path('admin/', include('adminapp.urls', namespace='adminapp')),

    # path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from django import forms

from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryForm(forms.ModelForm):
    discount = forms.IntegerField(label='Скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    # def clean_price(self):
    #     pass

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from adminapp.forms import ShopUserAdminEditForm, ProductCategoryForm, ProductForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product
from django.db.models import F
# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     context = {
#         'object_list': ShopUser.objects.all().order_by('-is_active')
#     }
#     return render(request, 'adminapp/users_list.html', context)

class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users_list.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return ShopUser.objects.filter(is_superuser=False)


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('adminapp:users'))
    else:
        user_form = ShopUserRegisterForm()
    context = {
        'form': user_form
    }
    return render(request, 'adminapp/user_form.html', context)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    current_users = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        user_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=current_users)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('adminapp:users'))
    else:
        user_form = ShopUserAdminEditForm(instance=current_users)
    context = {
        'form': user_form
    }
    return render(request, 'adminapp/user_form.html', context)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    current_users = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        current_users.is_active = False
        current_users.save()
        return HttpResponseRedirect(reverse('adminapp:users'))

    context = {
        'object': current_users
    }
    return render(request, 'adminapp/user_delete.html', context)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    context = {
        'object_list': ProductCategory.objects.all()
    }
    return render(request, 'adminapp/categories_list.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def category_create(request):
#     if request.method == 'POST':
#         form = ProductCategoryForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('adminapp:categories'))
#     else:
#         form = ProductCategoryForm()
#     context = {
#         'form': form
#     }
#     return render(request, 'adminapp/category_form.html', context)

class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_form.html'
    # fields = '__all__'
    form_class = ProductCategoryForm
    success_url = reverse_lazy('adminapp:categories')


# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request, pk):
#     category_item = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         form = ProductCategoryForm(request.POST, instance=category_item)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('adminapp:categories'))
#     else:
#         form = ProductCategoryForm(instance=category_item)
#     context = {
#         'form': form
#     }
#     return render(request, 'adminapp/category_form.html', context)

class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_form.html'
    # fields = '__all__'
    form_class = ProductCategoryForm
    success_url = reverse_lazy('adminapp:categories')

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount/100))
        return super().form_valid(form)


# @user_passes_test(lambda u: u.is_superuser)
# def category_delete(request, pk):
#     pass

class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('adminapp:categories')

    def delete(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.success_url)

@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    category_item = get_object_or_404(ProductCategory, pk=pk)
    context = {
        'object_list': Product.objects.filter(category__pk=pk),
        'category': category_item
    }
    return render(request, 'adminapp/products_list.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def product_create(request, pk):
#     category_item = get_object_or_404(ProductCategory, pk=pk)
#
#     if request.method == 'POST':
#         product_form = ProductForm(request.POST, request.FILES)
#         if product_form.is_valid():
#             product_item = product_form.save()
#             return HttpResponseRedirect(reverse('adminapp:products', args=[product_item.category.pk]))
#     else:
#         product_form = ProductForm()
#     context = {
#         'form': product_form,
#         'category': category_item
#     }
#     return render(request, 'adminapp/products_form.html', context)

class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/products_form.html'
    form_class = ProductForm
    success_url = reverse_lazy('adminapp:categories')

    def _get_category(self):
        category_id = self.kwargs.get('pk')
        category_item = get_object_or_404(ProductCategory, pk=category_id)
        return category_item

    def get_success_url(self):
        return reverse('adminapp:products', args=[self._get_category().pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.method == 'GET':
            context_data['category'] = self._get_category()
        return context_data


@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    product_item = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        product_form = ProductForm(request.POST, request.FILES, instance=product_item)
        if product_form.is_valid():
            product_item = product_form.save()
            return HttpResponseRedirect(reverse('adminapp:products', args=[product_item.category.pk]))
    else:
        product_form = ProductForm(instance=product_item)
    context = {
        'form': product_form,
        'category': product_item.category
    }
    return render(request, 'adminapp/products_form.html', context)


@user_passes_test(lambda u: u.is_superuser)
def product_delete(request, pk):
    product_item = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        product_item.is_active = False
        product_item.save()
        return HttpResponseRedirect(reverse('adminapp:products', args=[product_item.category.pk]))

    context = {
        'object': product_item
    }
    return render(request, 'adminapp/product_delete.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def product_read(request, pk):
#     product_item = get_object_or_404(Product, pk=pk)
#     context = {
#         'object': product_item
#     }
#     return render(request, 'adminapp/product_read.html', context)
#
class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="admin_container">
    <div class="h2 text-center head">
        Админка
    </div>
    <div class="admin_menu">
        <ul class="menu">
            <li>
                <a href="{% url 'index' %}"> На сайт</a>
            </li>
            <li>
                <a href="{% url 'adminapp:users' %}">Пользователи</a>
            </li>
            <li>
                <a href="{% url 'adminapp:categories' %}">Категории</a>
            </li>
            <li>
                <a href="{% url 'basketapp:basket' %}" class="basket">
                    <span>
                        {% if basket %}
                            {{ basket.0.total_cost|floatformat:0 }} руб.<br>
                            ({{ basket.0.total_quantity }} шт)
                        {% endif %}
                    </span>
                </a>
            </li>
        </ul>
    </div>
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

adminapp/templates/adminapp/categories_list.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="categories_list">
        <a href="{% url 'adminapp:category_create' %}" class="btn btn-primary">Добавить категорию</a>
        {% for item in  object_list %}
            <div class="category_record"{% if not item.is_active %}style="opacity: 0.5" {% endif %}>
                <div class="category_name">{{ item.name }}</div>
                <div class="category_actions">
                    <a class="btn btn-info" style="margin-bottom: 5px"
                       href="{% url 'adminapp:category_update' item.pk %}">Изменить</a>
                    <a class="btn btn-info" style="margin-bottom: 5px"
                       href="{% url 'adminapp:category_delete' item.pk %}">Удалить</a>
                    <a class="btn btn-info" style="margin-bottom: 5px" href="{% url 'adminapp:products' item.pk %}">Продукты</a>
                </div>
            <div class="category_desc">{{ item.description }}</div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
<p>Увереный что хотите удалить категорию {{ object.name }}?</p>
    <form method="post">
    {% csrf_token %}
    <input type="submit" value="Уверен!"/>
    </form>
    <a href="{% url 'adminapp:categories' %}" class="btn btn-primary">Нет, я передумал</a>
{% endblock %}

adminapp/templates/adminapp/category_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Сохранить">

    </form>
    <a href="{% url 'adminapp:categories' %}">К списку категорий</a>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
<p>Увереный что хотите удалить товар {{ object.name }}?</p>
    <form method="post">
    {% csrf_token %}
    <input type="submit" value="Уверен!"/>
    </form>
    <a href="{% url 'adminapp:users' %}" class="btn btn-primary">Нет, я передумал</a>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="product_read">
        <div class="product_name">
            Продукт<strong>{{ object.category.name|title }} /
            {{ object.name|title }}</strong>
        </div>
        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
             alt="{{ object.name }}">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <button>
                    <a href={% url 'adminapp:product_update' object.pk %}>
                        редактировать
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'adminapp:product_delete' object.pk %}>
                        удалить
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'adminapp:products' object.category.pk %}>
                        назад
                    </a>
                </button>
            </p>
        </div>
        <div class="product_desc">
            <b>краткая информация</b>
            <p>{{ object.short_desc }}</p>
            <br><br>
            <b>подробная информация</b>
            <p>{{ object.description }}</p>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/products_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Сохранить">

    </form>
    <a href="{% url 'adminapp:products' category.pk %}">К списку товаров</a>
{% endblock %}

adminapp/templates/adminapp/products_list.html
{% extends 'adminapp/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="products_list">
        <a href="{% url 'adminapp:product_create' category.pk %}" class="btn btn-primary">Добавить товар</a>
        {% for item in  object_list %}
            <div class="product_record"{% if not item.is_active %}style="opacity: 0.5" {% endif %}>
                <div class="product_name">{{ item.name }}</div>
{#                <img src="/media/{{ item.image }}"/>#}
                <img src="{{ item.image|media_for_products }}"/>
                <div class="product_actions">
                    <a class="btn btn-info" style="margin-bottom: 5px"
                       href="{% url 'adminapp:product_update' item.pk %}">Изменить</a>
                    <a class="btn btn-info" style="margin-bottom: 5px"
                       href="{% url 'adminapp:product_delete' item.pk %}">Удалить</a>
                    <a class="btn btn-info" style="margin-bottom: 5px" href="{% url 'adminapp:product_read' item.pk %}">Посмотреть</a>
                </div>
                <div class="summary">
                    Цена: {{ item.price }} руб
                    Колличество: {{ item.quantity }} шт
                </div>
                <div class="product_desc">
                    {{ item.description }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
<p>Увереный что хотите удалить пользщователя {{ object.username }}?</p>
    <form method="post">
    {% csrf_token %}
    <input type="submit" value="Уверен!"/>
    </form>
    <a href="{% url 'adminapp:users' %}" class="btn btn-primary">Нет, я передумал</a>
{% endblock %}

adminapp/templates/adminapp/user_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Сохранить">

    </form>
    <a href="{% url 'adminapp:users' %}">К списку пользователей</a>
{% endblock %}

adminapp/templates/adminapp/users_list.html
{% extends 'adminapp/base.html' %}
{% load my_tags %}

{% block content %}
    <div class="users_list">
        <a class="btn btn-primary" style="color: white" href="{% url 'adminapp:user_create' %}">Добавить
            пользователя</a>
        {% for item in object_list %}
            <div class="users_record"{% if not item.is_active %}style="opacity: 0.5" {% endif %}>
                <div class="user_avatar">
{#                    <img src="/media/{{ item.avatar|default:'users/phone.png' }}"/>#}
                    <img src="{{ item.avatar|media_for_users }}"/>
                </div>
                <div class="user_role">
                    {% if item.is_superuser %}
                        Администратор
                    {% else %}
                        Пользователь
                    {% endif %}
                    <a class="btn btn-info" href="{% url 'adminapp:user_update' item.pk %}">Изменить</a>
                    <br><br>
                    <a class="btn btn-info" href="{% url 'adminapp:user_delete' item.pk %}">Удалить</a>
                </div>
                <div class="user_name">
                    <p>{{ item.username }}</p>
                    <p>{{ item.get_full_name }}</p>
                </div>
                <div class="user_age">{{ item.age }}</div>
                <div class="user_email">{{ item.email }}</div>
            </div>

        {% endfor %}

    </div>
{% endblock %}