authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify')
]

basketapp/urls.py
from django.urls import path, include
from basketapp import views as basketapp

app_name = 'basketapp'


urlpatterns = [
    path('', basketapp.basket, name= 'basket'),
    path('add/<int:pk>/', basketapp.basket_add, name='basket_add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='basket_remove'),
    path('edit/<int:pk>/<quantity>/', basketapp.basket_edit, name='basket_edit'),
]

geekshop_2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('contacts/', mainapp.contact, name='contact'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basketapp')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
    path('admin/', include('adminapp.urls', namespace='adminapp')),

    # path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path, include
from mainapp import views as mainapp

app_name = 'products'


urlpatterns = [
    path('', mainapp.products, name='products'),
    path('<int:pk>/', mainapp.products, name='products_category'),
    path('<int:pk>/<int:page>/', mainapp.products, name='product_paginate'),
    path('product/<int:pk>/', mainapp.product, name='product')


]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, verbose_name='Название')
    image = models.ImageField(upload_to='products/', blank=True)
    short_desc = models.CharField(max_length=255, blank=True)
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена', default=0)
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Колличество')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} {self.category}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

mainapp/views.py
import http
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from mainapp.models import Product, ProductCategory



def get_hot_product():
    products_list = Product.objects.all()

    return random.sample(list(products_list), 1)[0]


def get_same_products(hot_product):
    same_products_list = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)

    return same_products_list[:3]


def index(request):
    products_list = Product.objects.all()[:4]
    print(products_list.query)

    context = {
        'title': 'мой магазин',
        'products': products_list,
    }
    return render(request, 'mainapp/index.html', context)


def products(request, pk=None, page=1):
    links_menu = ProductCategory.objects.all()

    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all()
            category_item = {'name': 'Все', 'pk': 0}
        else:
            category_item = get_object_or_404(ProductCategory, pk=pk)
            products_list = Product.objects.filter(category__pk=pk)

        # page = request.GET.get('page', 1)
        paginator = Paginator(products_list, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'links_menu': links_menu,
            'products': products_paginator,
            'category': category_item,
        }

        return render(request, 'mainapp/products_list.html', context)
    hot_product = get_hot_product()
    context = {
        'links_menu': links_menu,
        'title': "Товары",
        'hot_product': hot_product,
        'same_products': get_same_products(hot_product),
    }
    return render(request, 'mainapp/products.html', context)


def contact(request):
    links_menu = ProductCategory.objects.all()
    context = {
        'links_menu': links_menu,
        'title': "Товары",
    }
    return render(request, 'mainapp/contact.html', context)


def product(request, pk):
    links_menu = ProductCategory.objects.all()
    context = {
        'links_menu': links_menu,
        'product': get_object_or_404(Product, pk=pk),
    }
    return render(request, 'mainapp/product.html', context)

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{{ title|default:"Магазин"|title }}</title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
</head>
<body>
<div class="container">
    {% block  content %}

    {% endblock %}
    <div class="clr"></div>

	</div>

{{ some_date|date:'d-m-Y' }}
{% block footer %}
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB {% now 'd-m-Y' %}</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
</div>
{% endblock %}

</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% block content %}
    <div class="hero">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
        <h1>наши контакты</h1>
    </div>

    <div class="location">
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="slider">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png'%}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>
    {{some_value}}

    <div class="featured">
        <div class="featured-menu">
                <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png'%}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            {% for product in products %}
            <div class="block">
                <a href="{% url 'basketapp:basket_add' product.pk %}"><img src="/media/{{ product.image }}" alt="">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png'%}" alt="img">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.short_desc }} </p>
                    </div>
                </a>
            </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc_projects_menu.html' %}

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ product.image }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <h3 class="red">{{ product.category.name }}</h3>
                <p class="price"> {{ product.price|floatformat:0 }} <span>руб</span></p>
                <a href="{% url 'basketapp:basket_add' product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>{{ product.short_desc }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc_projects_menu.html' %}

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ hot_product.image }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price|floatformat:0 }} <span>руб</span></p>
                <a href="{% url 'basketapp:basket_add' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>{{ hot_product.short_desc }}</p>
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png'%}" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in same_products %}
                <div class="block">
                    <a href="{% url 'basketapp:basket_add' product.pk %}"><img src="/media/{{ product.image }}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.short_desc}}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc_projects_menu.html' %}


        <div class="products_list">
            <div class="title clearfix">
                <h2>
                    Категория: "{{ category.name|title }}"
                </h2>
                <div class="paginator">
                    {% if products.has_previous %}
                        <a href="{% url 'products:product_paginate' category.pk products.previous_page_number %}"><</a>
                    {% endif %}
                    <span class="current">
                        страница {{ products.number }} из {{ products.paginator.num_pages }}
                    </span>
                    {% if products.has_next %}
                        <a href="{% url 'products:product_paginate' category.pk products.next_page_number %}">></a>
                    {% endif %}
                </div>

            </div>
            <div class="category-products clearfix">

                {% for product in products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}">
                            <img src="/media/{{ product.image }}" alt="product">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

{% endblock %}